# Basic Site Settings
locale                   : "Shenzhen-CN"
site_theme               : "default"
title                    : "Juzhong Wei"
title_separator          : "-"
name                     : &name "Juzhong Wei"
description              : &description "Juzhong Wei's Academic Homepage"

url                      : "https://Moustachego.github.io"
baseurl                  : ""
repository               : "Moustachego/Moustachego.github.io"

author:
  avatar           : "profile.png"
  name             : "Juzhong Wei"
  bio              : "Graduate student in Computer Science"
  location         : "Shenzhen, China"
  employer         : "Beijing University of Posts and Telecommunications"
  email            : "weijzh@pcl.ac.cn"

  orcid            : "https://orcid.org/0009-0002-0756-3589"
  github           : "Moustachego"


  publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'
